### PR TITLE
fix-search-#207

### LINKED ISSUE #207: fix search
child of #167
add search for tx hash
fix search for keyblock hash (land on generation page instead keyblock page)

### PR DESCRIPTION
**Pull request by artem-rozhkov-dev-optima**
closes #207

### CODE REVIEW

**Comment by ror-shubham** [comment]
@artem-rozhkov-dev-optima please make a PR into develop.

**Comment by artem-rozhkov-dev-optima** [comment]
I have changeg it to develop

**Comment by artem-rozhkov-dev-optima** [comment]
changed by https://github.com/aeternity/aepp-blockchain-explorer/pull/214

**Comment by artem-rozhkov-dev-optima** [comment]
changed by #214

**Pull request closed without merging**
