### PR TITLE
[Work In Progress] Implementation of Dario's new designs

### PR DESCRIPTION
**Pull request by sadiqevani**
## THIS IS A WORK IN PROGRESS PR

This branch is being used to add the new designs in the blockchain explorer, its a scaffold for the new designs.

Currently working on it is Emil (@emilsomm), and Dario (@darioaschero) is leading the new designs.

### CODE REVIEW

**Comment by ricricucit** [comment]
@sadiqevani please do this PR towards `develop-new-ui` branch

**Comment by sadiqevani** [comment]
@emilsomm is working on this!

**Comment by emilsomm** [comment]
@ricricucit and the rest of the team have changed this. So the root branch for the new UI is now [develop-new-ui](https://github.com/aeternity/aepp-blockchain-explorer/tree/develop-new-ui)

**Comment by ricricucit** [comment]
@emilsomm I think you have to check what's in this branch and if this branch is useful at all.....because it might not be.

**Pull request closed without merging**
