### PR TITLE
 Process node data in vuex store

### PR DESCRIPTION
**Pull request by davidyuk**
* Extraction common data processing code into Vuex store from components
* Reducing of request amount, faster UI rendering in case of navigation in history, opening details page after list viewing
* Page can subscribe to new blocks, they will be pushed by reactive variables

### CODE REVIEW

**Comment by dadaphl** [comment]
For my understanding a store should be used to manage data that are shared between components (screens). Can you please elaborate why data, that is just used inside one component (for example market stats or address) should be saved in the store?

I think the pattern, that each screen needs to `this.unsubscribe()` in `beforeDestroy` is error prone. I 
would rather have a global single interval to check the current `blockheight` in the background.

Transaction menu link is not underlined anymore, probably has to do with the added suffix in the url. I think the default link should not have a pagination offset in the url. 

For the future I demand smaller, more specific commits. Reviewing +374 −556 LOC in one or two commit is simply unpractical.

**Comment by davidyuk** [comment]
I'm not sure a component should fetch data every time when it is displayed. I propose to extract this code into the store and fetch data only once. After that, we can implement custom update strategy if it is necessary. Moving code that implements data fetching to the store will make component simpler and probably will be easier to test it. Also, I think it is better to have all code that responsible for communication with a server in one place for upgrading in case of API changes and easier reusing of common functionality. Of course, the practical improvement of the account page is only that navigation in history is faster and no internet connection needed until the page is not reloaded.

I have added subscribeToLastBlocks mixin, that unsubscribes automatically.

Path params in the transaction list are reverted, I will send it in separate PR.

**Comment by dadaphl** [comment]
please implement the custom update strategy now and add it to the PR. it's important, that the explorer always reflects the current state of the node. 
I'm concerned that vuex store  gets bloated and eats up all the memory when I stay on the explorer for a long time. Is it a legit concern?
I have to admit, that cashing things in the frontend seems like premature optimization at this stage. Probably when the explorer gets live, frontend caching will not help scaling. We will need to build a middleware with database anyways.

**Comment by davidyuk** [comment]
I can't find any memory leaks except interval for `currentTime` updating should be cleared when a component is destroying. It is fixed in #11.

**Comment by davidyuk** [comment]
Market stats, accounts, and node state updated every 10 seconds by `pollAction` mixin, it has replaced `subscribeToLastBlocks` mixin.

Storing request in the store is more optimization for UI (reducing flickering) than reducing requests for a backend. Epoch node should be super scalable because of Erlang I would like to try it first.

**Pull request merged**
