### PR TITLE
[Proposal] Component restructuring and pattern update

### PR DESCRIPTION
**Pull request by sqevani**
### Task
_Component restructuring and pattern update_

### Description
_The blockchain explorer is a little bit unstructured and follows a mild structure in terms of components internally (not aepp-components), so I would like to propose a folder (component) structure that i've thought off the past year working on a Vue application in my current company_

### Flow
_First, the overall main concepts in the folder structure I would like to propose is the separation of concerns_

1. __tags__ are stateless components that serve only a specific job
2. __sections__ are stateful views, but that are not big / complex enough to have their own route
3. __views__ are views that include state and business logic and have their own route and are stand alone from other views

screen shot 2018-06-09 at 15 28 37

--- 

- the overall file structure should separate CSS, from JS, and HTML, in the long-term this can be beneficial and decrease the amount of things that get mixed together.

- In case there's similar components in terms of layout but differ in functionality, they can be nested, and in terms of component naming they follow the pattern of: `tag-[component name]-[child-component name]`

screen shot 2018-06-09 at 15 33 57

---

- sections include things such as headers, sidebars, and any component that needs to keep some global state on show in the application, and generally they're included into the "route.js" file into views, 

- The same concept as the tags applies to the sections, where internal components of the header are included as children of the section, these tags are section specific, which makes them not reusable, so keeping them in there makes the logic easier, and the developer does not have to jump between places.

screen shot 2018-06-09 at 16 01 04

---

- Views are state based global components that are managed by routes, so, when you think of a view, depending on how the application logic follows, the views have to have specific structuring.

- In the image below its the "auth" view which includes several children-views for the authentication of the user into the application.

screen shot 2018-06-09 at 16 04 35

---

__These might be an overkill for a small application like this, and i'm not looking to implement everything as described above, but take the best parts of the structure and apply it to the blockchain explorer, as it might make it easier to logic about views/sections/tags, since given that a "view" or a "tag" or a "section" will need change, since everything is encapsulated it makes it easier to pull apart and replace it with different things.__

### CODE REVIEW

**Comment by sqevani** [comment]
@dadaphl

**Comment by dadaphl** [comment]
> **tags** are stateless components that serve only a specific job

find the name not very descriptive to be honest, even misleading. why not just call it `components`?

> **sections** are stateful views, but that are not big / complex enough to have their own route

atm this is called `partials`

> **views** are views that include state and business logic and have their own route and are stand 
 alone from other views

thats called `screens`

Please check other aepps in the aeternity org for a naming system that might be already established. Lets not reinvent the wheel. Please focus on adding features and not change stuff back and forth according to ones personal preferences. There must be a really good reason why we should change the names as you proposed. Then we should follow this naming system in all aepps. Is it worth it?

**Comment by dadaphl** [comment]
> the overall file structure should separate CSS, from JS, and HTML, in the long-term this can be beneficial and decrease the amount of things that get mixed together.

We had this discussion before and agreed to keep everything together in a `.vue` file. Please elaborate why its worth the time and communication overhead?

Please get in touch with @davidyuk who advocated to keep it all in `.vue` file?

**Comment by dadaphl** [comment]
I think, whatever we decide it should be published as a 'best practice' guide and followed in all aepps.

**Comment by dadaphl** [comment]
@davidyuk please have a look at this proposal

**Comment by davidyuk** [comment]
> Please focus on adding features and not change stuff back and forth according to ones personal preferences.

I agree with Philipp.

> These might be an overkill for a small application like this

Yes, it is. Most of aepps are quite simple, also we are extracting common components to components package that makes less code in aepps repositories.

We have a lot of developers and it is easier to choose more obvious conventions. Also, it is an open-source project and probably better to keep out conventions simpler for contributions by developers outside of aeternity. At least proposed convention is not checkable by eslint, so reviewer should manually check it in every pull request.

- every component should solve a specific representative task (not-representative logic should be handled by store)
- components should be enough small to be reusable by other components

So we shouldn't have big components that can be reasonable to split into CSS, JS, and HTML files.

**Comment by sadiqevani** [comment]
> Yes, it is. Most of aepps are quite simple, also we are extracting common components to components package that makes less code in aepps repositories.

> We have a lot of developers and it is easier to choose more obvious conventions. Also, it is an open-source project and probably better to keep out conventions simpler for contributions by developers outside of aeternity. At least proposed convention is not checkable by eslint, so reviewer should manually check it in every pull request.

Long-term this can be easily fixed by adding some check to ESLint, most of the stuff are open source and are plugin based.

> - every component should solve a specific representative task (not-representative logic should be handled by store)

Agree.

> - components should be enough small to be reusable by other components
So we shouldn't have big components that can be reasonable to split into CSS, JS, and HTML files.

Though, no matter how many tiny components you build, you'll always come back to face reality that life is not perfect 😃, so you'll always have need for components that are stateful (which are partials in this case)

But the idea of the split is to reduce code clutter in `.vue` components, also side effects of this would be that you would be using `.js, .scss, .html` in your editor, which can be recognized by code completion software and syntax highlighters, instead of the custom `.vue` extension.

Also, one thing I had to do before was to include `i18n` into the application, so in a way with these structures, different part of a component are split into different files, but within the same folder, so easier to reason, and also long-term easily split into npm packages (if needed)

**Comment by davidyuk** [comment]
> you'll always come back to face reality that life is not perfect

The question was we should or shouldn't separate component into files by extension: it can happen in some edge cases, but should not be mandatory. 

> that you would be using .js, .scss, .html in your editor, which can be recognized by code completion software and syntax highlighters

As I see, you IDE supports vue templates. I don't like split component into several files by extension, because this code usually is tight connected and you should too frequent switch between editor tabs to work with it.

**Comment by dadaphl** [comment]
Ok @sadiqevani whats gonna happen with this PR? Can we close it?

**Comment by dadaphl** [comment]
ok, lets close this for now and move conversation to your new repo. If we are going to adopt it in explorer, we will create a new PR.

**Pull request closed without merging**
