### PR TITLE
replace div fields with field component and remove redundant timedata…

### PR DESCRIPTION
**Pull request by emilsomm**
… from time label

### CODE REVIEW

**Comment by davidyuk** [comment]
This PR has the same changes as #60?

**Comment by emilsomm** [comment]
Unfortunatly, this was my first branch and the consecutive two branches #59 and #60 was branched out from that. They should probably have been rebased, to keep them more clean, as each branch were quite focused.

**Comment by davidyuk** [comment]
Yes, it would be nice to rebase #60 with removing of "replace div fields with field component" commit.

**Comment by ricricucit** [comment]
closing, because of changes already included in [this PR](https://github.com/aeternity/aepp-blockchain-explorer/pull/60)

**Pull request closed without merging**
