### PR TITLE
Updated to latest api and added apache example

### PR DESCRIPTION
**Pull request by kryztoval**
The latest commit points to the naked api, /v1/ is no longer needed in the proxy.

### CODE REVIEW

**Comment by kryztoval** [comment]
Are you saying I can actually point the wallet directly to the endpoint without having to go thru apache?

Let me check that

**Comment by davidyuk** [comment]
Yes, it works on my computer. Actually, it may be easier to use a public testet: https://sdk-testnet.aepps.com/

**Comment by kryztoval** [comment]
Oh yeah, it works! It would still not let me connect to it it always says:
`Failed to load http://sdk-testnet.aepps.com/api: Redirect from 'http://sdk-testnet.aepps.com/api' to 'https://sdk-testnet.aepps.com/api' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. `

So I HAVE to run it locally to be able to connect to it if I am on chrome. but I do not need a proxy. which is nice.

**Comment by davidyuk** [comment]
@kryztoval try to add `https` prefix like [here](https://github.com/aeternity/aepp-blockchain-explorer/pull/80/files#diff-f579cccc964135c7d644c7b2d3b0d3ecR1)

**Comment by kryztoval** [comment]
Ok, closing this since it is no longer necesary to provide cors indirectly for http

**Comment by kryztoval** [comment]
Using that https prefix the sdk-testnet work, how do I secure my local node behind ssl? is that a setting on epoch or are they using a proxy? Since I am pretty sure trying to reach my port directly via https won't connect as my current settings do not provide this.

If it is a proxy i can set it up, basically using the same settings but using enable ssl. But if it is not... what am i missing?

This may be a question for epoch though. If it is I will place it on epoch.

**Comment by davidyuk** [comment]
> This may be a question for epoch though. If it is I will place it on epoch.

Actually yes.

As I know epoch doesn't support ssl, so a reverse proxy should be used.

**Comment by kryztoval** [comment]
@davidyuk Ok then, thank you, a reverse proxy it is.

**Pull request closed without merging**
